### ISSUE TITLE
Add CSS for better look and feel

### ISSUE THREAD

**Issue by razorblack** [treaknite/TextSearch#4]
Modify styles.css file to add CSS

**Comment by Palakkk** [comment]
can I work on this issue?

**Comment by razorblack** [comment]
Yes! sure.

**Comment by AjjlalAhmed** [comment]
can I also work on this issue?

**Comment by riyajha2305** [comment]
can i work on this issue?

**Comment by razorblack** [comment]
@riyajha2305 @AjjlalAhmed Feel free to work on this issue or any other in the Treaknite organization.

**Comment by dayanand-g** [comment]
can you please assign me to this issue?

**Comment by dayanand-g** [comment]
Hey there,
Am done with my PR, so please kindly merge into it.

Thank you.

**Comment by dayanand-g** [comment]
Sir,
It's showing like the project is not participating in the Hacktoberfest, so please kindly accept my request and add 
'Hacktoberfest-accepted' label to my PR Or else add 'Hacktoberfest' label to your repo.
Please kindly do it sir, coz it is my first contribution towards to the Haktoberfest.

Thank you.

**Comment by razorblack** [comment]
> Hey there, Am done with my PR, so please kindly merge into it.
> 
> Thank you.

Sorry for the delay! Thanks for contributing to our project, I looked at the changes you made. Glad to know it is your first contribution towards opensource. But the issue already got resolved by the PR #6 so I can't merge yours. 

- If you still waiting for your first contribution then you can work on issue [#2](https://github.com/treaknite/treaknite/issues/2)
